# Generated by Django 6.0 on 2025-12-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcations',
            fields=[
                ('ref_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('narration', models.CharField()),
                ('debit_amount', models.FloatField(default=0.0)),
                ('credit_amount', models.FloatField(default=0.0)),
                ('closing_balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
