# Generated by Django 6.0 on 2025-12-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='ref_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
