# Generated by Django 6.0 on 2025-12-23 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transcations_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='value_date',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
