# Generated by Django 6.0 on 2025-12-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transcations_value_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transcations',
            name='narration',
            field=models.CharField(null=True),
        ),
    ]
