# Generated by Django 6.0 on 2025-12-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transcations_date_alter_transcations_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transcations',
            name='ref_no',
            field=models.CharField(max_length=50),
        ),
    ]
