# Generated by Django 6.0 on 2025-12-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transcations_id_alter_transcations_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='narration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
