# Generated by Django 6.0 on 2025-12-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_transcations_narration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='narration',
            field=models.TextField(null=True),
        ),
    ]
