# Generated by Django 6.0 on 2025-12-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transcations_category_transcations_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
