# Generated by Django 6.0 on 2025-12-25 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transcations_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='currency',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
