# Generated by Django 6.0 on 2025-12-28 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_transcations_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='merchant',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
