# Generated by Django 6.0 on 2025-12-28 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_transcations_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
    ]
