# Generated by Django 6.0 on 2026-01-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transcations_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='ref_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
