# Generated by Django 6.0 on 2026-01-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_transcations_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='cheque_info',
            field=models.CharField(null=True),
        ),
    ]
