# Generated by Django 6.0 on 2026-01-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_transcations_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcations',
            name='user',
        ),
    ]
