# Generated by Django 6.0 on 2026-01-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_transcations_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fie_name', models.CharField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transcations',
            name='color',
        ),
        migrations.AlterField(
            model_name='transcations',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.category'),
        ),
        migrations.CreateModel(
            name='CategoryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='transcations',
            name='uploaded_version',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='version', to='api.versionhistory'),
            preserve_default=False,
        ),
    ]
