# Generated by Django 6.0 on 2026-01-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_category_versionhistory_remove_transcations_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versionhistory',
            old_name='fie_name',
            new_name='file_name',
        ),
    ]
