# Generated by Django 6.0 on 2026-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_versionhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryColor',
        ),
    ]
