# Generated by Django 6.0 on 2026-01-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_category_color_delete_categorycolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uploaded_version',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='category_version', to='api.versionhistory'),
            preserve_default=False,
        ),
    ]
